name: iblenv
dependencies:
  - python=3.10
  - ipython
  - matplotlib
  - numba
  - numpy
  - pandas
  - scikit-learn
  - scipy >=1.4.1
  - seaborn
  - statsmodels
  - tqdm
  - pip
  - pip:
    - iblutil
    - ibllib
    - iblapps
    - ibl-neuropixel
    - ONE-api
    - phylib
    - phy
    - pynrrd
    - slidingRP
    - neurencoding
